### ISSUE TITLE
Please support WorkerThread like the previous version

### ISSUE THREAD

**Issue by wann2** [AgoraIO/Basic-Video-Broadcasting#43]
Hi,

I have been using Basic-Video-Broadcasting that using WorkerThread till 2.9.0.
And I have been using it the Video Call together in my App.

But suddenly the version 2.9.1 and the sample sources does not support workerThread, but Application. It means that RtcEngine sites in AgoraApplication.java.
It is absolutely hard work, because the new sample source can not apply to my App.
Furthermore there is not enough explanation in details and the structure of the source has been changed fully.

Could you please support the sources that uses WorkerThread like the previous?

**Comment by wann2** [comment]
Or Clould please guide how can I move the RtcEngine logic in AgoraApplication into Activity file like LiveActivity.java or RtcBaseActivity.java?

**Comment by plutoless** [comment]
hi you can find previous version in existing tags:
https://github.com/AgoraIO/Basic-Video-Broadcasting/tree/2.9.1

However we will put future works in latest version. WorkerThread is not a must but a rather recommended approach when you are implementing large project with better thread management. It's up to your choice whether to use it or not. We removed it mainly because it will introduce a lot more code files while we would rather developers to focus on our SDK relevant APIs.
Maybe you can illustrate which part you dont' quite understand and i will try to answer here.

**Comment by wann2** [comment]
Now I have applied the new Broadcast sample to my app.
At first, it was difficult to understand the new broadcast sample by putting RtcEngine in AgoraApplication.java, but later I found out that Application is a Common Class, so I can apply it to my app. As a result, the new approach was much more concise and better than WorkerThread.

When will the samples for VideoCall and VoiceCall be updated and provided like a new broadcast sample?

**Comment by plutoless** [comment]
@wann2  glad to hear that! it's on our radar and we will adapt Open Video Call in upcoming 1-2 releases.

**Comment by wann2** [comment]
Hi Qianze,

I have a question.

In VideoGridContainer.java, MAX_USER = 4 is set.

Does MAX_USER mean up to maximum 4 Broadcasters?
Or does it mean up to maximum 4 Audiences?


Best,
WannWann Lee

**Comment by plutoless** [comment]
up to 4 broadcasters. you can literately have unlimited audience in one channel. the MAX_USER variable is used to layout the broadcasters. but this is just a limitation set on UI level within this demo. agora sdk supports up to 17 broadcasters in one channel.
